version: "3.7"

services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=${EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - le_data:/letsencrypt
    networks:
      - traefik
  
  nginx:
    depends_on:
      - wordpress
    image: nginx:${NGINX_VERSION}
    restart: always
    environment:
      - NGINX_HOST=${HOST_NAME}
    volumes:
      - wp_data:/var/www/html
      - ./wordpress/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/themes:/var/www/html/wp-content/themes
      - ./nginx/conf.d:/etc/nginx/conf.d
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`${HOST_NAME}`)
      - traefik.http.routers.wordpress.tls=true
      - traefik.http.routers.wordpress.tls.certresolver=le
    networks:
      traefik:
      wordpress:
  
  wordpress:
    depends_on:
      db:
        condition: service_healthy
    image: wordpress:${WORDPRESS_VERSION}
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DEBUG: ${WP_DEBUG}
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis Ojbect Cache */
        define( 'WP_REDIS_HOST', 'redis' );
        define( 'WP_REDIS_PORT', 6379 );
        /* Nginx Cache */
        define( 'RT_WP_NGINX_HELPER_CACHE_PATH', '/var/run/nginx-cache' );

    volumes:
      - wp_data:/var/www/html
      - ./wordpress/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/themes:/var/www/html/wp-content/themes
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - wordpress  

  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
      - db_socket:/var/lib/mysqld
      - ./mysql_conf/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$${DB_ROOT_PASSWORD}
      interval: 5s
      retries: 10
    networks:
      - wordpress

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - wordpress

  watchtower:
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /path/to/db_data
      o: bind
  db_socket:
    driver: local
    driver_opts:
      type: none
      device: /path/to/db_socket
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /path/to/wp_data
      o: bind
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: /path/to/redis_data
      o: bind
  le_data:
    driver: local
    driver_opts:
      type: none
      device: /path/to/le_data
      o: bind
networks:
  traefik:
    driver: bridge
    name: traefik
  wordpress:
    driver: bridge
    name: wordpress
